templates:
  class: info.magnolia.module.site.templates.ReferencingPrototypeTemplateSettings
  prototypeId: training-templating-website:pages/prototype-of-all-page-templates
  availability:
    templates:
      home:
        id: training-templating-website:pages/home
      default:
        id: training-templating-website:pages/default
i18n:
  class: info.magnolia.cms.i18n.DefaultI18nContentSupport
  enabled: true
  fallbackLocale: en
  locales:
    en:
      country: ''
      enabled: true
      language: en
    de:
      country: ''
      enabled: true
      language: de
    fr:
      country: ''
      enabled: true
      language: fr
    it:
      country: ''
      enabled: true
      language: it
 
mappings:
  website:
    URIPrefix:
    handlePrefix: /training
    repository: website  