layout:                # Configuraci칩n del dise침o del iniciador de aplicaciones.
  groups:              # Refereciar a la organizaci칩n de las apps por grupos.
    - name: marketing  # Se define un grupo llamado "marketing".
      apps:            # Se dispone a especificar que apps van dentro del grupo de marketing.
        - name: events # Dentro del grupo "marketing", hay una aplicaci칩n llamada "events".
