[#if myString1?has_content]
  [#-- Hacer algo si myString no es nulo ni vacío --]
[#elseif myString2?has_content]
  [#-- Hacer algo si myString no es nulo ni vacío --]
[#else]
  [#-- Hacer algo si myString es nulo o vacío --]
[/#if]
